# Makefile
#
# Canonical development and automation entry points for the bootstrap
# project.
#
# Developers edit the modular source files listed in SOURCE_FILES. Users consume
# one of the generated dist/bootstrap*.bash artifacts produced by make build or
# make all.

SHELL := /bin/bash
.SHELLFLAGS := -eu -o pipefail -c

DIST_DIR := dist
DIST_DEV_SCRIPT := $(DIST_DIR)/bootstrap.dev.bash
DIST_SCRIPT := $(DIST_DIR)/bootstrap.bash
DIST_MIN_SCRIPT := $(DIST_DIR)/bootstrap.min.bash
DIST_SCRIPTS := $(DIST_DEV_SCRIPT) $(DIST_SCRIPT) $(DIST_MIN_SCRIPT)
DIST_CHECKSUMS := $(addsuffix .sha256,$(DIST_SCRIPTS))
LEGACY_CHECKSUMS := $(addsuffix .256,$(DIST_SCRIPTS))
SOURCE_FILES := lib/build-metadata.bash lib/runtime/exit-codes.bash lib/runtime/context.bash lib/runtime/config.bash lib/runtime/privilege.bash lib/runtime/logging.bash lib/runtime/recovery.bash lib/runtime/diagnostics.bash lib/backend/diagnostics.bash lib/manifest/parser.bash lib/planner/action-record.bash lib/planner/planner.bash lib/resolver/resolved-action.bash lib/backend/apt.bash lib/backend/apk.bash lib/backend/dnf.bash lib/backend/backend.bash lib/resolver/resolver.bash lib/executor/execution-result.bash lib/executor/apt.bash lib/executor/apk.bash lib/executor/dnf.bash lib/executor/executor.bash src/bootstrap.bash
TESTS_DIR := tests/
TEST_SCRIPTS := ${TESTS_DIR}/*.bats
TEST_RESULTS_DIR := test-results

VENDOR_DIR := vendor
DEPENDENCY_MANIFEST := dependencies.txt
BASHDEPS := $(VENDOR_DIR)/bashdeps.bash
BASHDEPS_VERSION := 0.0.6
BASHDEPS_URL := https://github.com/wesley-dean/bashdeps/releases/download/v$(BASHDEPS_VERSION)/bashdeps.bash
BASHDEPS_SHA256 := bb6c807fa12c010950bda06172ac0611d278c57aca1f8352f41502d0d76b4e6c
DOXYGEN_BASH_FILTER := $(VENDOR_DIR)/doxygen-bash.awk
BASH_MINIFIER := $(VENDOR_DIR)/bash-minifier.bash
REFERENCE_DOC_DIR := doc/reference

E2E_TEST_DIR := ${TESTS_DIR}/e2e
E2E_TEST_IMAGE_PREFIX := bootstrap_e2e_tmp_image
E2E_TEST_TARGETS := test-e2e-apt test-e2e-apk test-e2e-dnf

VERSION ?= $(shell git describe --tags --always 2>/dev/null || printf '0.0.0-dev')
BUILD_COMMIT ?= $(shell git rev-parse --short=12 HEAD 2>/dev/null || printf 'unknown')
BUILD_DATE ?= $(shell git show -s --format=%cI HEAD 2>/dev/null || printf 'unknown')

.PHONY: all build check checksums clean deps deps-check distclean docs docs-clean FORCE format test test-report test-e2e test-e2e-platform test-e2e-apt test-e2e-apk test-e2e-dnf test-e2e-ubuntu test-e2e-alpine test-e2e-redhat verify-bashdeps

##
# Synchronize development dependencies, then build the consumer artifacts.
#
# The recursive Make invocation keeps ordering explicit under parallel Make.
# Plain `make build` remains independent of dependency synchronization and does
# not create or verify vendor state.
#
all: deps
	$(MAKE) --no-print-directory build

##
# Build all standalone Bootstrap distribution artifacts and checksums.
#
# This target consumes already-prepared Bash-Minifier state. It does not acquire
# or verify dependencies and therefore remains network-free.
#
build: $(DIST_SCRIPTS) $(DIST_CHECKSUMS)
	rm -f $(LEGACY_CHECKSUMS)

##
# Assemble the fully commented development artifact from maintained source.
#
$(DIST_DEV_SCRIPT): $(SOURCE_FILES)
	mkdir -p "$(DIST_DIR)"
	{ \
		printf '%s\n' '#!/usr/bin/env bash'; \
		printf '%s\n' '#'; \
		printf '%s\n' '# Generated by make build. Do not edit directly.'; \
		printf '%s\n' '# Source files: $(SOURCE_FILES)'; \
		printf '\n'; \
		printf 'BOOTSTRAP_VERSION=%q\n' "$(VERSION)"; \
		printf 'BOOTSTRAP_BUILD_DATE=%q\n' "$(BUILD_DATE)"; \
		printf 'BOOTSTRAP_BUILD_COMMIT=%q\n' "$(BUILD_COMMIT)"; \
		printf '\n'; \
		cat $(SOURCE_FILES); \
	} >"$@.tmp"
	chmod 0755 "$@.tmp"
	mv "$@.tmp" "$@"

##
# Derive the ordinary artifact by removing full-line comments from the complete
# assembled development artifact while preserving its shebang.
#
$(DIST_SCRIPT): $(DIST_DEV_SCRIPT)
	sed '1b; /^[[:space:]]*#/d' "$<" >"$@.tmp"
	chmod 0755 "$@.tmp"
	mv "$@.tmp" "$@"

##
# Derive the minified artifact from the complete comment-stripped artifact.
#
# Bash-Minifier is manifest-managed dependency state. A missing dependency is an
# actionable build failure rather than a reason for build to access the network.
#
$(DIST_MIN_SCRIPT): $(DIST_SCRIPT)
	@test -f "$(BASH_MINIFIER)" || { \
		printf '%s\n' 'Missing build dependency vendor/bash-minifier.bash; run make deps or make all' >&2; \
		exit 1; \
	}
	bash "$(BASH_MINIFIER)" -F <"$(DIST_SCRIPT)" >"$@.tmp"
	chmod 0755 "$@.tmp"
	mv "$@.tmp" "$@"

##
# Generate a SHA-256 checksum companion for one built executable artifact.
#
$(DIST_DIR)/%.bash.sha256: $(DIST_DIR)/%.bash
	@digest=''; \
	if command -v sha256sum >/dev/null 2>&1; then \
		digest="$$(sha256sum "$<" | awk '{print $$1}')"; \
	elif command -v shasum >/dev/null 2>&1; then \
		digest="$$(shasum -a 256 "$<" | awk '{print $$1}')"; \
	else \
		printf '%s\n' 'No SHA-256 command is available for build checksums' >&2; \
		exit 1; \
	fi; \
	printf '%s  %s\n' "$$digest" "$(notdir $<)" >"$@.tmp"; \
	mv "$@.tmp" "$@"

##
# Compatibility/convenience alias: successful build already creates checksums.
#
checksums: build

##
# Run ShellCheck against hand-maintained Bash source files.
#
# Generated distribution artifacts are intentionally excluded here. The checked
# source files are the source of truth, and make build derives all three consumer
# representations from them.
#
check:
	shellcheck $(SOURCE_FILES)

##
# Format hand-maintained Bash source files using shfmt.
#
format:
	shfmt -w $(SOURCE_FILES)

##
# Run the behavior-oriented Bats test suite against every executable flavor.
#
# Existing tests intentionally address dist/bootstrap.bash as the consumer path.
# The runner temporarily places each built flavor at that path, restores the
# ordinary stripped artifact after each run, and therefore applies the same
# observable-behavior contract to development, stripped, and minified output.
#
test: build
	@set -e; \
	backup="$(DIST_DIR)/.bootstrap.bash.test-original"; \
	cp "$(DIST_SCRIPT)" "$$backup"; \
	trap 'mv -f "$$backup" "$(DIST_SCRIPT)"' EXIT; \
	for entry in \
		'development|$(DIST_DEV_SCRIPT)' \
		'stripped|'"$$backup" \
		'minified|$(DIST_MIN_SCRIPT)'; do \
		label="$${entry%%|*}"; \
		artifact="$${entry#*|}"; \
		cp "$$artifact" "$(DIST_SCRIPT)"; \
		chmod 0755 "$(DIST_SCRIPT)"; \
		printf 'Testing %s artifact\n' "$$label"; \
		bats $(TEST_SCRIPTS); \
	done

##
# Run the Bats suite against every flavor and emit one JUnit file per flavor.
#
test-report: build
	@mkdir -p "$(TEST_RESULTS_DIR)"
	@set -e; \
	backup="$(DIST_DIR)/.bootstrap.bash.test-original"; \
	cp "$(DIST_SCRIPT)" "$$backup"; \
	trap 'mv -f "$$backup" "$(DIST_SCRIPT)"' EXIT; \
	for entry in \
		'development|$(DIST_DEV_SCRIPT)' \
		'stripped|'"$$backup" \
		'minified|$(DIST_MIN_SCRIPT)'; do \
		label="$${entry%%|*}"; \
		artifact="$${entry#*|}"; \
		cp "$$artifact" "$(DIST_SCRIPT)"; \
		chmod 0755 "$(DIST_SCRIPT)"; \
		bats --formatter junit $(TEST_SCRIPTS) >"$(TEST_RESULTS_DIR)/bats-$${label}.xml"; \
	done

##
# Force the bootstrap file target to validate cached bytes whenever requested.
#
FORCE:

##
# Bootstrap the pinned released bashdeps executable used to process
# dependencies.txt.
#
# Make directly owns only this bootstrap dependency. Correct cached bytes avoid
# network access. Missing or mismatched bytes are replaced only after a staged
# download matches the committed SHA-256 digest.
#
$(BASHDEPS): FORCE
	@mkdir -p "$(VENDOR_DIR)"
	@verify_hash() { \
		path=$$1; \
		if command -v sha256sum >/dev/null 2>&1; then \
			printf '%s  %s\n' "$(BASHDEPS_SHA256)" "$$path" | sha256sum -c - >/dev/null 2>&1; \
		elif command -v shasum >/dev/null 2>&1; then \
			actual="$$(shasum -a 256 "$$path" | awk '{print $$1}')"; \
			[[ "$$actual" == "$(BASHDEPS_SHA256)" ]]; \
		else \
			return 2; \
		fi; \
	}; \
	if ! command -v sha256sum >/dev/null 2>&1 && ! command -v shasum >/dev/null 2>&1; then \
		printf '%s\n' 'No SHA-256 verification command is available for bashdeps.bash' >&2; \
		exit 1; \
	fi; \
	if [[ -f "$@" ]] && verify_hash "$@"; then \
		chmod 0755 "$@"; \
		exit 0; \
	fi; \
	if ! command -v curl >/dev/null 2>&1; then \
		printf '%s\n' 'curl is required to bootstrap bashdeps.bash' >&2; \
		exit 1; \
	fi; \
	tmp="$@.tmp"; \
	trap 'rm -f "$$tmp"' EXIT; \
	curl -fsSL "$(BASHDEPS_URL)" -o "$$tmp"; \
	if ! verify_hash "$$tmp"; then \
		printf '%s\n' 'Downloaded bashdeps.bash does not match the committed SHA-256 digest' >&2; \
		exit 1; \
	fi; \
	chmod 0755 "$$tmp"; \
	mv "$$tmp" "$@"; \
	trap - EXIT

##
# Verify the already-present bashdeps bootstrap without network access or repair.
#
verify-bashdeps:
	@test -x "$(BASHDEPS)" || { \
		printf '%s\n' 'Missing or non-executable bashdeps bootstrap; run make deps' >&2; \
		exit 1; \
	}
	@if command -v sha256sum >/dev/null 2>&1; then \
		if ! printf '%s  %s\n' "$(BASHDEPS_SHA256)" "$(BASHDEPS)" | sha256sum -c - >/dev/null 2>&1; then \
			printf '%s\n' 'bashdeps.bash does not match the committed SHA-256 digest; run make deps' >&2; \
			exit 1; \
		fi; \
	elif command -v shasum >/dev/null 2>&1; then \
		actual="$$(shasum -a 256 "$(BASHDEPS)" | awk '{print $$1}')"; \
		if [[ "$$actual" != "$(BASHDEPS_SHA256)" ]]; then \
			printf '%s\n' 'bashdeps.bash does not match the committed SHA-256 digest; run make deps' >&2; \
			exit 1; \
		fi; \
	else \
		printf '%s\n' 'No SHA-256 verification command is available for bashdeps.bash' >&2; \
		exit 1; \
	fi

##
# Synchronize manifest-managed development dependencies through released bashdeps.
#
# This target may use the network and may repair dependency state.
#
deps: $(BASHDEPS) $(DEPENDENCY_MANIFEST)
	$(MAKE) --no-print-directory verify-bashdeps
	"$(BASHDEPS)" sync "$(DEPENDENCY_MANIFEST)"

##
# Verify bootstrap and manifest-managed state without network access or repair.
#
deps-check: verify-bashdeps $(DEPENDENCY_MANIFEST)
	"$(BASHDEPS)" verify "$(DEPENDENCY_MANIFEST)"

##
# Remove generated Doxygen reference documentation.
#
# Reference output is generated locally or by CI and is intentionally excluded
# from source control.
#
docs-clean:
	rm -rf "$(REFERENCE_DOC_DIR)"

##
# Generate browsable reference documentation with Doxygen.
#
# The Doxygen filter is manifest-managed dependency state. Documentation
# generation consumes already-prepared bytes and deliberately does not invoke
# dependency synchronization or network acquisition.
#
docs:
	@test -f "$(DOXYGEN_BASH_FILTER)" || { \
		printf '%s\n' 'Missing documentation dependency vendor/doxygen-bash.awk; run make deps or make all' >&2; \
		exit 1; \
	}
	$(MAKE) --no-print-directory docs-clean
	chmod 0755 "$(DOXYGEN_BASH_FILTER)"
	mkdir -p "$(REFERENCE_DOC_DIR)"
	doxygen Doxyfile

##
# Run all currently enabled containerized end-to-end test environments.
#
# The enabled platform list is intentionally explicit.
#
test-e2e: $(E2E_TEST_TARGETS)

##
# Run the Ubuntu/APT end-to-end test environment.
#
test-e2e-apt: build
	$(MAKE) test-e2e-platform E2E_PLATFORM=ubuntu

##
# Run the Alpine/APK end-to-end test environment.
#
test-e2e-apk: build
	$(MAKE) test-e2e-platform E2E_PLATFORM=alpine

##
# Run the RedHat-family/DNF end-to-end test environment.
#
test-e2e-dnf: build
	$(MAKE) test-e2e-platform E2E_PLATFORM=redhat

##
# Backward-compatible alias for the Ubuntu/APT end-to-end test environment.
#
test-e2e-ubuntu: test-e2e-apt

##
# Backward-compatible alias for the Alpine/APK end-to-end test environment.
#
test-e2e-alpine: test-e2e-apk

##
# Backward-compatible alias for the RedHat-family/DNF end-to-end test environment.
#
test-e2e-redhat: test-e2e-dnf

##
# Run one platform-specific containerized end-to-end test environment.
#
# Each platform context lives under tests/e2e/<platform>. The generated
# bootstrap.bash artifact is copied into that context immediately before the
# image is built and removed again during cleanup.
#
test-e2e-platform: build
	@if [[ -z "$${E2E_PLATFORM:-}" ]]; then \
		printf '%s\n' 'E2E_PLATFORM is required' >&2; \
		exit 2; \
	fi; \
	context="${E2E_TEST_DIR}/$${E2E_PLATFORM}"; \
	image="${E2E_TEST_IMAGE_PREFIX}_$${E2E_PLATFORM}"; \
	bootstrap="$${context}/bootstrap.bash"; \
	if [[ ! -f "$${context}/Dockerfile" ]]; then \
		printf 'No e2e Dockerfile found for platform: %s\n' "$${E2E_PLATFORM}" >&2; \
		exit 2; \
	fi; \
	cp "${DIST_SCRIPT}" "$${bootstrap}"; \
	trap 'rm -f "'"$${bootstrap}"'"; docker image rm "'"$${image}"'" >/dev/null 2>&1 || true' EXIT; \
	docker build -t "$${image}" -f "$${context}/Dockerfile" "$${context}"; \
	docker run --rm "$${image}"

clean:
	rm -rf "$(DIST_DIR)"

##
# Remove all generated local build, test, documentation, and dependency state.
#
distclean: clean docs-clean
	rm -rf "$(VENDOR_DIR)"
	rm -rf "$(TEST_RESULTS_DIR)"
