# Makefile
#
# Canonical development and automation entry points for the bootstrap
# project.
#
# Phase 1 introduces a generated distribution artifact. Developers edit
# the modular source files listed in SOURCE_FILES. Users consume the
# generated dist/bootstrap.bash artifact produced by make all.

SHELL := /bin/bash
.SHELLFLAGS := -eu -o pipefail -c

DIST_DIR := dist
DIST_SCRIPT := $(DIST_DIR)/bootstrap.bash
DIST_CHECKSUM := $(DIST_SCRIPT).sha256
SOURCE_FILES := lib/build-metadata.bash lib/runtime/exit-codes.bash lib/runtime/context.bash lib/runtime/config.bash lib/runtime/privilege.bash lib/runtime/logging.bash lib/runtime/recovery.bash lib/runtime/diagnostics.bash lib/backend/diagnostics.bash lib/manifest/parser.bash lib/planner/action-record.bash lib/planner/planner.bash lib/resolver/resolved-action.bash lib/backend/apt.bash lib/backend/backend.bash lib/resolver/resolver.bash lib/executor/execution-result.bash lib/executor/apt.bash lib/executor/executor.bash src/bootstrap.bash
TESTS_DIR := tests/
TEST_SCRIPTS := ${TESTS_DIR}/*.bats
TEST_RESULTS_DIR := test-results

E2E_TEST_DIR := ${TESTS_DIR}/e2e
E2E_TEST_IMAGE_PREFIX := bootstrap_e2e_tmp_image
E2E_TEST_PLATFORMS := ubuntu

VERSION ?= $(shell git describe --tags --always 2>/dev/null || printf '0.0.0-dev')
BUILD_COMMIT ?= $(shell git rev-parse --short=12 HEAD 2>/dev/null || printf 'unknown')
BUILD_DATE ?= $(shell git show -s --format=%cI HEAD 2>/dev/null || printf 'unknown')

.PHONY: all check checksums clean distclean format test test-report test-e2e test-e2e-platform test-e2e-ubuntu

all: $(DIST_SCRIPT)

$(DIST_SCRIPT): $(SOURCE_FILES)
	mkdir -p "$(DIST_DIR)"
	{ \
		printf '%s\n' '#!/usr/bin/env bash'; \
		printf '%s\n' '#'; \
		printf '%s\n' '# Generated by make all. Do not edit directly.'; \
		printf '%s\n' '# Source files: $(SOURCE_FILES)'; \
		printf '\n'; \
		printf 'BOOTSTRAP_VERSION=%q\n' "$(VERSION)"; \
		printf 'BOOTSTRAP_BUILD_DATE=%q\n' "$(BUILD_DATE)"; \
		printf 'BOOTSTRAP_BUILD_COMMIT=%q\n' "$(BUILD_COMMIT)"; \
		printf '\n'; \
		cat $(SOURCE_FILES) \
    | sed '/^#/d'; \
	} >"$@.tmp"
	chmod 0755 "$@.tmp"
	mv "$@.tmp" "$@"

##
# Run ShellCheck against hand-maintained Bash source files.
#
# The generated distribution artifact is intentionally excluded here. The
# checked source files are the source of truth, and make all assembles them into
# the release artifact.
#
check:
	shellcheck $(SOURCE_FILES)

##
# Format hand-maintained Bash source files using shfmt.
#
format:
	shfmt -w $(SOURCE_FILES)

##
# Run the behavior-oriented Bats test suite.
#
# The generated distribution artifact is a prerequisite because tests exercise
# the executable users will receive rather than the modular source files.
#
test: $(DIST_SCRIPT)
	bats $(TEST_SCRIPTS)

test-report: $(DIST_SCRIPT)
	mkdir -p "$(TEST_RESULTS_DIR)"
	bats --formatter junit $(TEST_SCRIPTS) >"$(TEST_RESULTS_DIR)/bats.xml"

##
# Run all currently enabled containerized end-to-end test environments.
#
# The enabled platform list is intentionally explicit.  Alpine and RedHat-family
# directories exist as reserved test contexts, but they are not included until the
# corresponding APK and DNF backends are implemented.
#
test-e2e: $(addprefix test-e2e-,$(E2E_TEST_PLATFORMS))

##
# Run the Ubuntu/APT end-to-end test environment.
#
test-e2e-ubuntu: all
	$(MAKE) test-e2e-platform E2E_PLATFORM=ubuntu

##
# Run one platform-specific containerized end-to-end test environment.
#
# Each platform context lives under tests/e2e/<platform>.  The generated
# bootstrap.bash artifact is copied into that context immediately before the
# image is built and removed again during cleanup.
#
test-e2e-platform: all
	@if [[ -z "$${E2E_PLATFORM:-}" ]]; then \
		printf '%s\n' 'E2E_PLATFORM is required' >&2; \
		exit 2; \
	fi; \
	context="${E2E_TEST_DIR}/$${E2E_PLATFORM}"; \
	image="${E2E_TEST_IMAGE_PREFIX}_$${E2E_PLATFORM}"; \
	bootstrap="$${context}/bootstrap.bash"; \
	if [[ ! -f "$${context}/Dockerfile" ]]; then \
		printf 'No e2e Dockerfile found for platform: %s\n' "$${E2E_PLATFORM}" >&2; \
		exit 2; \
	fi; \
	cp "${DIST_SCRIPT}" "$${bootstrap}"; \
	trap 'rm -f "'"$${bootstrap}"'"; docker image rm "'"$${image}"'" >/dev/null 2>&1 || true' EXIT; \
	docker build -t "$${image}" -f "$${context}/Dockerfile" "$${context}"; \
	docker run --rm "$${image}"

##
# Generate SHA-256 checksums for release artifacts.
#
# The checksum file is written from inside the distribution directory so users
# can download bootstrap.bash and bootstrap.bash.sha256 into the same working
# directory and verify the artifact with sha256sum -c bootstrap.bash.sha256.
#
checksums: $(DIST_SCRIPT)
	cd "$(DIST_DIR)" && sha256sum "$(notdir $(DIST_SCRIPT))" >"$(notdir $(DIST_CHECKSUM))"

clean:
	rm -rf "$(DIST_DIR)"

##
# Remove all generated local build and test products.
#
# This target extends clean so a developer can return the repository to the
# closest practical equivalent of a fresh checkout without touching source
# files or downloaded dependencies.
#
distclean: clean
	rm -rf "$(TEST_RESULTS_DIR)"
