FROM ubuntu:24.04

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update \
 && apt-get install -y --no-install-recommends \
      bash \
      ca-certificates \
      curl \
 && rm -rf /var/lib/apt/lists/*

ENTRYPOINT ["/usr/bin/env", "bash", "/tmp/test.bash"]
WORKDIR /workspace

HEALTHCHECK NONE

COPY bootstrap.bash /tmp/
COPY e2e.manifest /tmp/
COPY test.bash /tmp/

